example_diff_output = [('change', 'Arena.coins', (283341, 283441)), ('change', 'GingerBread.coins', (362846, 362946)), ('change', 'Paintball.coins', (362846, 362946)), ('change', 'Quake.coins', (362846, 362946)), ('change', 'VampireZ.coins', (362846, 362946)), ('change', 'Walls.coins', (362846, 362946)), ('change', 'HungerGames.coins', (15135, 15235)), ('change', 'MurderMystery.coins', (20057, 20345)), ('change', 'MurderMystery.coins_pickedup', (487, 493)), ('change', 'MurderMystery.games', (112, 113)), ('change', 'MurderMystery.kills', (113, 117)), ('change', 'MurderMystery.wins', (72, 73)), ('change', 'MurderMystery.alpha_chance', (8, 9)), ('change', 'MurderMystery.bow_kills', (109, 113)), ('change', 'MurderMystery.bow_kills_MURDER_INFECTION', (109, 113)), ('change', 'MurderMystery.coins_pickedup_MURDER_INFECTION', (483, 489)), ('change', 'MurderMystery.games_MURDER_INFECTION', (111, 112)), ('change', 'MurderMystery.kills_MURDER_INFECTION', (109, 113)), ('change', 'MurderMystery.kills_as_survivor', (271, 279)), ('change', 'MurderMystery.kills_as_survivor_MURDER_INFECTION', (271, 279)), ('change', 'MurderMystery.total_time_survived_seconds', (5304, 5399)), ('change', 'MurderMystery.total_time_survived_seconds_MURDER_INFECTION', (5304, 5399)), ('change', 'MurderMystery.survivor_wins',																																																																																																																																																																																																																																																																																																																										 (72, 73)), ('change', 'MurderMystery.survivor_wins_MURDER_INFECTION', (72, 73)), ('change', 'MurderMystery.wins_MURDER_INFECTION', (71, 72)), ('change', 'MurderMystery.bow_kills_towerfall', (18, 22)), ('change', 'MurderMystery.bow_kills_towerfall_MURDER_INFECTION', (18, 22)), ('change', 'MurderMystery.coins_pickedup_towerfall', (102, 108)), ('change', 'MurderMystery.coins_pickedup_towerfall_MURDER_INFECTION', (102, 108)), ('change', 'MurderMystery.games_towerfall', (18, 19)), ('change', 'MurderMystery.games_towerfall_MURDER_INFECTION', (18, 19)), ('change', 'MurderMystery.kills_as_survivor_towerfall', (35, 43)), ('change', 'MurderMystery.kills_as_survivor_towerfall_MURDER_INFECTION', (35, 43)), ('change', 'MurderMystery.kills_towerfall', (18, 22)), ('change', 'MurderMystery.kills_towerfall_MURDER_INFECTION', (18, 22)), ('change', 'MurderMystery.survivor_wins_towerfall', (11, 12)), ('change', 'MurderMystery.survivor_wins_towerfall_MURDER_INFECTION', (11, 12)), ('change', 'MurderMystery.total_time_survived_seconds_towerfall', (4893, 5399)), ('change', 'MurderMystery.total_time_survived_seconds_towerfall_MURDER_INFECTION', (4893, 5399)), ('change', 'MurderMystery.wins_towerfall', (11, 12)), ('change', 'MurderMystery.wins_towerfall_MURDER_INFECTION', (11, 12))]

def convert_to_lists(t):
	return list(map(convert_to_lists, t)) if isinstance(t, (list, tuple)) else t

new_diff = convert_to_lists(example_diff_output)
for i in range(len(new_diff)):
	del new_diff[i][0]

